### ISSUE TITLE
[Minor] This is biutifule

### ISSUE THREAD

**Issue by Kiryonn** [NeosSkopos/ColoniesAndTechnologies#1]
The mod `Domum Ornamentum` version displays `${file.jarVersion}` on the `Modrinth App`
I'm not sure if it's an independant mod or an addition by your team, i'm not sure if the problem comes from the app either. But as the modpack devs, you probably would know better than i do and redirect to the right person.

![image](https://github.com/NeosSkopos/ColoniesAndTechnologies/assets/60699390/612913be-a976-4777-8a3e-1670e57d5fa2)

**Comment by NeosSkopos** [comment]
Interesting share. Learnt something new here.
I use Prism Launcher, so I didn't know that the Curseforge mods show up like this when using the Modrinth Launcher :).

Domum Ornamentum is one of the dependancies for the MineColonies mod - both of which are from the Curseforge website.
Whenever you see such a version indicator, it's probably because it's a Curseforge mod.
I credit the mod pages in the pack's description, but as for the specific version of the mod installed, it's usually the latest version available at the time of the modpack version's publication, unless specifically mentioned in my change history.
