### ISSUE TITLE
How to make a dedicated server?

### ISSUE THREAD

**Issue by memes-forever** [NeosSkopos/ColoniesAndTechnologies#11]
How to make a dedicated server?

I'm playing with friends, the build is not stable, it crashes from time to time...

**Comment by NeosSkopos** [comment]
I like your ticket, because this was exactly what I was working on my side recently, since Sunday. (I previously only used the pack by inviting friends with the Essential mod into my single player worlds, but since last weekend, I started to try host it on a server and I'm working on the issues we're finding.)

Just released version 49, which fixed some issues with hosting a server, but my most frustrating issue is still stuck with Heracles.
1. The Biome Particle Weather mod caused crashes whenever it started to rain. (known issue and developer no longer supports forge builds, so no fix planned for it - had to remove the mod, so that shouldn't cause random crashes anymore.)
2. Quests work when inviting someone into singleplayer via Essential mod, but on dedicated servers they prevent someone from logging in a second time. (You'll need to disable the Heracles mod on client and server. [Here)](https://github.com/terrarium-earth/Heracles/issues/223) is the link to the bug report.)
3. When setting up your server, exclude the following mods from your server's mod folder: (these are client-side only ones - I still plan on making these auto-rename to .client in v50)

> Panorama Screens, Footprint Particle, Embeddium, watermedia, better beds reforged, BiomeParticleWeather, cherished worlds, clean tooltips, completionist index, current game music track, distinguished potions, effect descriptions, equipment compare, essential, forgematica, helditemtooltips, improved sign editing, loading backgrounds, mafglib, mob plaques, modpack update checker, no resourcepack warnings, overflowing bars, seamless, slot cycler, splashy, trade uses, traveler's titles, WI Zoom, yeetus experimentus

I'll set up a more proper guide before closing this ticket and will also reference it in the modpack description on Modrinth when done. :)

**Comment by NeosSkopos** [comment]
Also, if you do have a crash, please send me your crash report file (you can just add it to this ticket).
It might be an issue I haven't encountered myself. (I usually try fixing the crashing issues as soon as I can, or at least warn people about it in the modpack description.)

**Comment by WimpieRatte** [comment]
Good news is that the quests bug has been fixed in Resourceful Lib 2.1.25.
I'll wait until that version goes live, then I'll update the pack again and do a proper tutorial for setting up a dedicated server.
v50 will make this task much easier, because you won't need to manually remove the client-side mods anymore.

**Comment by NeosSkopos** [comment]
I created the following video tutorial: https://youtu.be/krVubnOhKWQ
Will also link it in the modpack description.
