### ISSUE TITLE
[Minor] Flat isn't flat

### ISSUE THREAD

**Issue by Kiryonn** [NeosSkopos/ColoniesAndTechnologies#3]
- Modpack Version : 39

Creating a superflat world (which i often use for tests and build planification) ends up creating a regular one.

![2024-02-01_18 58 25](https://github.com/NeosSkopos/ColoniesAndTechnologies/assets/60699390/95abc42f-5c41-456a-8ae6-1b250485b7ab)

**Comment by NeosSkopos** [comment]
Thanks for reporting this!
I'll look into some solutions.
Definitely a good thing to have working. I'll also mention this in the known issues section of the pack's description until fixed, due to its usefulness.

**Comment by NeosSkopos** [comment]
Found a workaround.

To generate a superflat world, you'll have to:
1. _Temporarily_ disable the **Terralith** and **Tectonic** mods
2. Launch the game and create your new superflat world with creative mode
3. In the game, use Chunky to generate as many chunks/blocks as you wish. (E.g, type "/chunky radius 1000" (press enter), then "/chunky start" (press enter) in chat, to generate a 1000 block radius around spawn. More options: https://modrinth.com/plugin/chunky)
4. _**Remember to quit and re-enable the 2 mods before loading your normal worlds**_, to avoid risks with world generation glitches.

Unfortunately this is caused by a known vanilla Minecraft bug (https://bugs.mojang.com/browse/MC-260949), which causes all world-gen datapacks to be unable to properly support other world types. (These mods are actually data packs packaged as mods)
I learned this from the Terralith github: https://github.com/Stardust-Labs-MC/Terralith/issues/70

I'll keep an eye open for permanent fixes, but it looks like this is an inconvenience we'll have to live with for now until something solid is available.

(Side comment: Since the only villages in the pack that generate are the modded ones from CTOV, they might also not generate in a superflat world, so to have some vanilla villages appear in superflat, also temporarily disable the "Village Nullifier" mod.
