### ISSUE TITLE
[Rendering] Train doors

### ISSUE THREAD

**Issue by Kiryonn** [NeosSkopos/ColoniesAndTechnologies#4]
- modpack version : 39

## This is a create train door:
![2024-02-01_22 40 46](https://github.com/NeosSkopos/ColoniesAndTechnologies/assets/60699390/ea99078f-34f3-40dc-aaa5-a27ea5210122)

## Now we open it ... hmmm
![2024-02-01_22 40 52](https://github.com/NeosSkopos/ColoniesAndTechnologies/assets/60699390/6486879d-2812-4f71-b6a2-78029560fdaf)

## Wait a second, something isn't right !!
![2024-02-01_22 41 06](https://github.com/NeosSkopos/ColoniesAndTechnologies/assets/60699390/dba1409c-13cf-4778-bd3f-c1a44e0cac66)

**Comment by NeosSkopos** [comment]
Does it replace the rendering of the brick walls next to it?
I'll check this out and come back to you :).

**Comment by Kiryonn** [comment]
no it doesn't, i broke it so we can see better what's happening. Normaly it should open on the sides, but it opened as vanilla doors AND with the normal way it should open at the same time.

**Comment by NeosSkopos** [comment]
Wait, that's not how it's supposed to work then?
I remember testing that in my test world and thinking "this is cool how it combines a sliding and folding effect".
I did find it weird how the sound was gone when it had blocks on its sides though, but I didn't think much of it and carried on.

Maybe this is similar to the issue mods experience when Sodium is installed and needing Indium as well.
I'll do some testing around that, because I remember seeing an Indium equivalent for Forge released recently.

**Comment by Kiryonn** [comment]
> Wait, that's not how it's supposed to work then?

Not how i remember it at least.
The 2 others factor that made me realise it's not intended as well were the facts that the edge is a bit glichy and the "vanilla opening" wasn't animated, which is a weird thing from `Create`.

> this is cool how it combines a sliding and folding effect

The closest thing from that description would be "regular" create doors i believe.

**Comment by NeosSkopos** [comment]
> Not how i remember it at least. The 2 others factor that made me realise it's not intended as well were the facts that the edge is a bit glichy and the "vanilla opening" wasn't animated, which is a weird thing from `Create`.

Cool.
Couldn't get to this issue during this weekend, but will look into it in the future.

**Comment by NeosSkopos** [comment]
In the latest version this is now fixed
