### ISSUE TITLE
[Recipe] Vein Mining

### ISSUE THREAD

**Issue by Kiryonn** [NeosSkopos/ColoniesAndTechnologies#5]
There are 3 different Vein Mining books atm. One of them is craftable with (imo) a decently balanced recipe.
![image](https://github.com/NeosSkopos/ColoniesAndTechnologies/assets/60699390/d21871af-43f8-4d9f-bb26-67d38c33951d)

**Comment by NeosSkopos** [comment]
I remember one of the Vein Mining mods working more like excavation.
I'll look into the options for recipe updates for these.
Thanks for raising this! :D

**Comment by NeosSkopos** [comment]
Got feedback on this.
The 3 books you're seeing, are:
1. The Vein Mining enchantment from Vein Mining mod.
2. The Vein Mining enchantment from "CAWEZ'S Mantle to Stratus".
3. A Vein Mining "book" from "CAWEZ'S Mantle to Stratus".

Essentially, only 2 enchantments, because the 3rd (craftable) item is a different thing, but the developer of the "CAWEZ'S Mantle to Stratus" mod informed me that he will be renaming his Vein Mining to "Excavate", because it modifies the tool to mine a 3x3x1 area and not "vein mine", like the "Vein Mining" mod does.

So I'll leave this as is. I first considered removing the recipe to avoid the confusion, but in respect to the mod author, I'll leave it as is and it should resolve itself in the future with his future versions of his mod.
