### ISSUE TITLE
[Interaction] Can't put books in a Book Shelf

### ISSUE THREAD

**Issue by Kiryonn** [NeosSkopos/ColoniesAndTechnologies#9]
- Modpack version : 39

![2024-02-03_14 23 59](https://github.com/NeosSkopos/ColoniesAndTechnologies/assets/60699390/0e8805ff-b1f6-4626-bcf1-a18cf43d332a)
Also tested with regular books, instructions books (patchouli), book and quill. None of them work.

**Comment by NeosSkopos** [comment]
I'll test it as soon as I can, but I remember there being a difference between book shelves from that mod and the normal shelves.
(So this might actually be behaving as intended, but I'll confirm.)

**Comment by NeosSkopos** [comment]
So far I tested the mod without any other mods - then it works fine.
So there's a mod conflict somewhere, that affects these bookshelves.

I'll need to dig deeper by adding mods sequentially, until I determine which mod causes the conflict.

**Comment by NeosSkopos** [comment]
Found the culprit: Lexicon
Removing this mod in version 40.
(I added it for people newer to Minecraft, but since I started adding quests, I don't think I need it anymore... especially if it breaks bookshelves.)

This is a known issue that was reported to the mod as well: https://legacy.curseforge.com/minecraft/mc-mods/lexicon/issues/3

**Comment by NeosSkopos** [comment]
Should now be sorted.
Version 40 is now live :)
